In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
%matplotlib inline

In [2]:
df = pd.read_csv("../data/MachineLearningRating_v3.txt", sep="|")
df.head()

C:\Users\YOGA 9I\AppData\Local\Temp\ipykernel_6448\455118313.py:1: DtypeWarning: Columns (0: CapitalOutstanding, 1: CrossBorder) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/MachineLearningRating_v3.txt", sep="|")

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [3]:
print(df.shape)
df.info()

(1000098, 52)
<class 'pandas.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  str
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  str
 5   LegalType                 1000098 non-null  str
 6   Title                     1000098 non-null  str
 7   Language                  1000098 non-null  str
 8   Bank                      854137 non-null   str
 9   AccountType               959866 non-null   str
 10  MaritalStatus             991839 non-null   str
 11  Gender                    990562 non-null   str
 12  Country                   1000098 non-null  str
 13  Province                  1000098 non-null  str
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  str
 16  SubCrestaZone             1000098 non-null  str
 17  ItemType                  1000098 non-null  str
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   str
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   str
 22  Model                     999546 non-null   str
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   str
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   str
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  str
 31  TrackingDevice            1000098 non-null  str
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   str
 34  WrittenOff                358197 non-null   str
 35  Rebuilt                   358197 non-null   str
 36  Converted                 358197 non-null   str
 37  CrossBorder               698 non-null      str
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  str
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  str
 43  CoverCategory             1000098 non-null  str
 44  CoverType                 1000098 non-null  str
 45  CoverGroup                1000098 non-null  str
 46  Section                   1000098 non-null  str
 47  Product                   1000098 non-null  str
 48  StatutoryClass            1000098 non-null  str
 49  StatutoryRiskType         1000098 non-null  str
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(1), str(35)
memory usage: 390.1+ MB

In [4]:
df["TransactionMonth"] = pd.to_datetime(df["TransactionMonth"])
df["VehicleIntroDate"] = pd.to_datetime(df["VehicleIntroDate"], errors="coerce")

C:\Users\YOGA 9I\AppData\Local\Temp\ipykernel_6448\3983187443.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["VehicleIntroDate"] = pd.to_datetime(df["VehicleIntroDate"], errors="coerce")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  datetime64[us]
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  str
 5   LegalType                 1000098 non-null  str
 6   Title                     1000098 non-null  str
 7   Language                  1000098 non-null  str
 8   Bank                      854137 non-null   str
 9   AccountType               959866 non-null   str
 10  MaritalStatus             991839 non-null   str
 11  Gender                    990562 non-null   str
 12  Country                   1000098 non-null  str
 13  Province                  1000098 non-null  str
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  str
 16  SubCrestaZone             1000098 non-null  str
 17  ItemType                  1000098 non-null  str
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   str
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   str
 22  Model                     999546 non-null   str
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   str
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   datetime64[us]
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  str
 31  TrackingDevice            1000098 non-null  str
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   str
 34  WrittenOff                358197 non-null   str
 35  Rebuilt                   358197 non-null   str
 36  Converted                 358197 non-null   str
 37  CrossBorder               698 non-null      str
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  str
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  str
 43  CoverCategory             1000098 non-null  str
 44  CoverType                 1000098 non-null  str
 45  CoverGroup                1000098 non-null  str
 46  Section                   1000098 non-null  str
 47  Product                   1000098 non-null  str
 48  StatutoryClass            1000098 non-null  str
 49  StatutoryRiskType         1000098 non-null  str
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), datetime64[us](2), float64(11), int64(4), object(1), str(33)
memory usage: 390.1+ MB

In [6]:
df.describe()

,UnderwrittenCoverID,PolicyID,TransactionMonth,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,VehicleIntroDate,CustomValueEstimate,NumberOfVehiclesInFleet,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,1.000098e+06,1.000098e+06,1000098,1.000098e+06,9.995460e+05,1.000098e+06,999546.000000,999546.000000,999546.000000,999546.000000,999546,2.204560e+05,0.0,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06
mean,1.048175e+05,7.956682e+03,2015-02-28 10:49:29.147424,3.020601e+03,5.487770e+07,2.010225e+03,4.046642,2466.743258,97.207919,4.019250,2008-04-20 17:04:04.990425,2.255311e+05,NaN,6.041727e+05,1.178757e+02,6.190550e+01,6.486119e+01
min,1.000000e+00,1.400000e+01,2013-10-01 00:00:00,1.000000e+00,4.041200e+06,1.987000e+03,0.000000,0.000000,0.000000,0.000000,1977-10-01 00:00:00,2.000000e+04,NaN,1.000000e-02,0.000000e+00,-7.825768e+02,-1.200241e+04
25%,5.514300e+04,4.500000e+03,2015-01-01 00:00:00,8.270000e+02,6.005692e+07,2.008000e+03,4.000000,2237.000000,75.000000,4.000000,2007-11-01 00:00:00,1.350000e+05,NaN,5.000000e+03,3.224800e+00,0.000000e+00,0.000000e+00
50%,9.408300e+04,7.071000e+03,2015-04-01 00:00:00,2.000000e+03,6.005842e+07,2.011000e+03,4.000000,2694.000000,111.000000,4.000000,2010-10-01 00:00:00,2.200000e+05,NaN,7.500000e+03,8.436900e+00,2.178333e+00,0.000000e+00
75%,1.391900e+05,1.107700e+04,2015-06-01 00:00:00,4.180000e+03,6.005842e+07,2.013000e+03,4.000000,2694.000000,111.000000,4.000000,2012-04-01 00:00:00,2.800000e+05,NaN,2.500000e+05,9.000000e+01,2.192982e+01,0.000000e+00
max,3.011750e+05,2.324600e+04,2015-08-01 00:00:00,9.870000e+03,6.506535e+07,2.015000e+03,10.000000,12880.000000,309.000000,6.000000,2014-09-01 00:00:00,2.655000e+07,NaN,1.263620e+07,7.442217e+04,6.528260e+04,3.930921e+05
std,6.329371e+04,5.290039e+03,NaN,2.649854e+03,1.360381e+07,3.261391e+00,0.294020,442.800640,19.393256,0.468314,NaN,5.645157e+05,NaN,1.508332e+06,3.997017e+02,2.302845e+02,2.384075e+03

In [7]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

NumberOfVehiclesInFleet    1000098
CrossBorder                 999400
CustomValueEstimate         779642
Rebuilt                     641901
Converted                   641901
WrittenOff                  641901
NewVehicle                  153295
Bank                        145961
AccountType                  40232
Gender                        9536
MaritalStatus                 8259
VehicleType                    552
make                           552
mmcode                         552
Model                          552
Cylinders                      552
bodytype                       552
kilowatts                      552
NumberOfDoors                  552
VehicleIntroDate               552
cubiccapacity                  552
CapitalOutstanding               2
dtype: int64

In [8]:
(df.isnull().sum() / len(df)) * 100

UnderwrittenCoverID           0.000000
PolicyID                      0.000000
TransactionMonth              0.000000
IsVATRegistered               0.000000
Citizenship                   0.000000
LegalType                     0.000000
Title                         0.000000
Language                      0.000000
Bank                         14.594670
AccountType                   4.022806
MaritalStatus                 0.825819
Gender                        0.953507
Country                       0.000000
Province                      0.000000
PostalCode                    0.000000
MainCrestaZone                0.000000
SubCrestaZone                 0.000000
ItemType                      0.000000
mmcode                        0.055195
VehicleType                   0.055195
RegistrationYear              0.000000
make                          0.055195
Model                         0.055195
Cylinders                     0.055195
cubiccapacity                 0.055195
kilowatts                     0.055195
bodytype                      0.055195
NumberOfDoors                 0.055195
VehicleIntroDate              0.055195
CustomValueEstimate          77.956560
AlarmImmobiliser              0.000000
TrackingDevice                0.000000
CapitalOutstanding            0.000200
NewVehicle                   15.327998
WrittenOff                   64.183810
Rebuilt                      64.183810
Converted                    64.183810
CrossBorder                  99.930207
NumberOfVehiclesInFleet     100.000000
SumInsured                    0.000000
TermFrequency                 0.000000
CalculatedPremiumPerTerm      0.000000
ExcessSelected                0.000000
CoverCategory                 0.000000
CoverType                     0.000000
CoverGroup                    0.000000
Section                       0.000000
Product                       0.000000
StatutoryClass                0.000000
StatutoryRiskType             0.000000
TotalPremium                  0.000000
TotalClaims                   0.000000
dtype: float64

In [9]:
df["LossRatio"] = df["TotalClaims"] / df["TotalPremium"]
df["Margin"] = df["TotalPremium"] - df["TotalClaims"]

In [10]:
overall_loss_ratio = df["TotalClaims"].sum() / df["TotalPremium"].sum()
print(overall_loss_ratio)

1.0477452570332206